### ISSUE TITLE
Iconos de APIs se pisan durante la federación

### ISSUE THREAD

**Issue by poligarcia** [datosgobar/portal-andino-theme#281]
Cuando corre la federacion parece que se borra el icono que se le asigno a un recurso de tipo API.

**Comment by chdigiorno** [comment]
Ver error que surge con los recursos federados:

```
Traceback (most recent call last):
  File "/usr/lib/ckan/default/src/ckan/ckan/model/modification.py", line 88, in notify
    observer.notify(entity, operation)
  File "/theme/ckanext/gobar_theme/plugin.py", line 131, in notify
    self._prepare_data_for_storage_outside_datajson(arguments_list_to_store, entity_dict, 'resources')
  File "/theme/ckanext/gobar_theme/plugin.py", line 115, in _prepare_data_for_storage_outside_datajson
    return gobar_helpers.store_object_data_excluded_from_datajson(object_type, parameters_to_send)
  File "/theme/ckanext/gobar_theme/helpers.py", line 480, in store_object_data_excluded_from_datajson
    return config[object_dict_name][data_dict.get('id', data_dict_id)]
KeyError: u'fa3fdae8-ba0d-4788-a2ad-f25c9aba8a10_federado_11_federado_11.2'
```
Reemplazar:

    return config[object_dict_name][data_dict.get('id', data_dict_id)]

por
    return config[object_dict_name].get(data_dict.get('id', data_dict_id), None)
